import { Contact, SiteHeader } from "../components";
export const metadata = { title: "About — Olusola Kalejaiye" };
const photos=["zigRPIJL9NRtgpu7NopZP3bGVE","SZeUszEIPpla2h06DypKKlxiY","56Fsa9D4iEQuSPhUlenmkdMgyMo","0IFjnCzGks1epRYHqo4YvhHdPfY","c4zqEWakghSM3JdcULMbRTgAqxk"].map(id=>`https://framerusercontent.com/images/${id}.png?scale-down-to=1024`);
const captures=["YFnvLIQCwpmyjjAVtmBMWwrqpQ","d2K8J7eg79E043lylsHa80EXAc","ONClEG2WTBeIPohMHJLyRhLxNY"].map(id=>`https://framerusercontent.com/images/${id}.jpeg?scale-down-to=1024`);
export default function AboutPage(){return <main><SiteHeader/><article className="aboutFramer">
  <header className="aboutIntro"><h1>A curious human, learning through every iteration.</h1><h2>Partner, plant-dad, music curator, amateur footballer, movie-lover.</h2></header>
  <div className="aboutCollage">{photos.map((src,i)=><img src={src} alt="A moment from Olusola's life" key={src} className={'photo'+i}/>)}</div>
  <section className="aboutBlock"><p className="sectionLabel">My Story</p><h2>From Physics to Pixels</h2><p>My journey into UX is a bit of a winding road. I started out in studying physics for my bachelor&apos;s (true story), dabbled in graphic design for fun during university, and landed my first design job at Switch Entrepreneurs Magazine. But deep down, I was curious about more—how people think, what makes businesses tick, and how tech can tie it all together.</p><p>That curiosity led me to the Stutern Graduate Accelerator Bootcamp in 2019 and into UX design full-time, starting at Heroshe. Since then, I&apos;ve been lucky to work across Fintech, Web3, and e-commerce, shipping products that have:</p><ul><li>🚀 Helped raise $20M+ in funding</li><li>🌍 Been used by over 200M people worldwide</li><li>💳 Handled $100M+ in transactions</li></ul><a className="inlineButton" href="https://drive.google.com/file/d/1cEmHf_ziqA3yJbRUIYv0rh4gWCOitIte/view?usp=drive_link">Get my CV</a></section>
  <section className="aboutBlock"><p className="sectionLabel">My Philosophy</p><h2>Design with Curiosity and Care,<br/>Design for Simplicity and Clarity</h2><p>Design is about more than pixels or wireframes, it&apos;s about respect: for the user’s time, their attention, and their humanity. That’s why my approach is always rooted in simplicity and clarity, stripping away the unnecessary to let what truly matters shine through.</p><p>To me, great design is what’s <em>left when everything unnecessary is stripped away.</em> I believe every pixel should serve a purpose—beautiful is good, but beautiful and functional? That’s the magic.</p><aside className="aboutQuote"><span>I strongly believe that…</span><strong>“Good design is invisible—it just works.”</strong></aside></section>
  <section className="aboutBlock aboutBeyond"><p className="sectionLabel">Beyond Design</p><h2>Movies, Music &amp; Photography</h2><p>I’m deep into the things that make life meaningful. I believe inspiration doesn’t only come from within the design world—it comes from the stories we consume, the places we explore, and the quiet moments we capture.</p><h3>Design is what I do—but it&apos;s not all I am.</h3><div className="interest"><h2>Movies</h2><p>I love films that make me think twice, linger longer, or hit just the right emotional note.</p><div className="movieRow"><article><img src="https://framerusercontent.com/images/CwuCZJnGzVeZ4g1xvC4lDY5gs.png?scale-down-to=512" alt="The Shawshank Redemption"/><strong>The Shawshank<br/>Redemption</strong></article><article><strong>The Lord of the<br/>Rings - Trilogy</strong></article><article><strong>The Big Bang<br/>Theory</strong></article></div></div><div className="interest"><h2>Photography</h2><p>Street photography is how I stay present. There’s something meditative about wandering through cities with a camera in hand.</p><div className="captureRow">{captures.map(src=><img src={src} alt="Street photography" key={src}/>)}</div><em>A few favorite captures—from Lagos, Birmingham, or wherever life takes me.</em></div><div className="interest"><h2>Music</h2><p>Music is my creative fuel—Burna Boy, Ed Sheeran, Asake—they&apos;re on repeat when I’m in flow. I curate playlists the same way I design: with intent, rhythm, and a feel for the moment.</p></div></section>
</article><Contact/></main>}
