import { notFound } from "next/navigation";
import { caseStudies } from "../../case-data";
import { Contact, SiteHeader } from "../../components";
const published = caseStudies.filter((s) => s.slug !== "conversational-ai");
const context: Record<string, { team: string; contributions: string; opening: string; challenge: string; shipped?: string; next: string[] }> = {
  "heritage-bank": { team: "2x Product Designer · 1x User Researcher · 1x Product Manager · 2x Mobile Developers · 2x Backend Developers", contributions: "UX Audit, Research, UX & UI Design", opening: "Heritage Bank is one of Nigeria’s commercial banks with over 2.3M depositors. Its mobile banking app had grown outdated, with clunky navigation, poor onboarding, inconsistent design, and no dark mode. These issues left users frustrated and stakeholders dissatisfied.", challenge: "How might we create a modern banking experience that makes onboarding, transfers and everyday actions clear, accessible and scalable?", next: ["mvno", "opscentral-case-study"] },
  mvno: { team: "2x Product Designer · 1x User Researcher · 1x Product Manager · 2x Mobile Developers · 2x Backend Developers", contributions: "Design, Strategy, Market Research & Usability Testing", opening: "Interswitch, the parent company of Verve with over 70M cardholders, wanted to build a direct-to-consumer channel beyond its traditional relationships through issuing banks and fintechs. Launching an MVNO under the Verve brand created an opportunity to deepen engagement with young people.", challenge: "How might we balance compliance, usability and adoption while helping young Nigerians stay connected, transact securely and be rewarded?", next: ["heritage-bank", "opscentral-case-study"] },
  "opscentral-case-study": { team: "Lead Product Designer @ Interswitch", contributions: "Design, Strategy, User Interviews", opening: "Interswitch processes over 1 billion transactions monthly across Africa. Partners often lacked a centralised way to track and manage transactions, forcing them to switch between back-office tools to investigate settlements, disputes and reports.", challenge: "How might we consolidate fragmented processes into a single, seamless experience that gives partners real-time transaction visibility?", next: ["heroshe-case-study", "heritage-bank"] },
  "heroshe-case-study": { team: "Full-time Designer at Heroshe", contributions: "Design, Strategy, User Interviews", opening: "Picture this: You find the perfect gadget on Amazon, but it can’t be delivered to your country. So you order and ship it to your freight-forwarder, and then… radio silence. The packages weren’t delayed or missing—but the updates were.", challenge: "How can we provide timely updates that keep users informed and confident about their shipments?", shipped: "https://framerusercontent.com/images/z3myjTjgaeus7bcMBDMbZhuks.png?scale-down-to=2048&width=2880&height=1616", next: ["opscentral-case-study", "heritage-bank"] },
};
export function generateStaticParams() { return published.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const s = published.find((item) => item.slug === slug); return { title: s ? s.title + " — Olusola Kalejaiye" : "Case Study" }; }

const heritageAssets = {
  onboarding: [
    "https://framerusercontent.com/images/KmtJB5MUmS6JSN7VviibqAacOw.gif?width=750&height=1624",
    "https://framerusercontent.com/images/4Fjav5Xaj1diQ6FGkV4x5VHYW4o.png?width=863&height=1771",
    "https://framerusercontent.com/images/YhrKqjqwiqeSxG8gchCKP2RplM.gif?width=375&height=812",
  ],
  home: [
    "https://framerusercontent.com/images/Hp4kz0gG6eqvRDrWE3vh9LH8EE0.gif?width=750&height=1624",
    "https://framerusercontent.com/images/aKhsqB55uLz4Vd1IgvY4rLoXuA.gif?width=750&height=1624",
  ],
  transfers: [
    "https://framerusercontent.com/images/9A2JWBwqOrox3a9Up6UBBZEVOeY.gif?width=886&height=1778",
    "https://framerusercontent.com/images/ieWwbss3aphoc9w0yPlUewIVLo.gif?width=750&height=1624",
  ],
  system: "https://framerusercontent.com/images/Db2azuiGf6jiXSXhuv6vK1JGs.gif?width=960&height=720",
};
function Visual({ src, alt }: { src: string; alt: string }) { return <div className="heritageVisual"><img src={src} alt={alt} /></div>; }
function HeritageCase() {
  return <main className="heritageCase"><header className="heritageTop"><a href="/cases">←&nbsp; Back</a><a href="#contact">Get in touch</a></header>
    <section className="heritageHero"><div><span className="heritageMark">HB</span><h1>Modernizing Heritage Bank&apos;s<br />Mobile Experience For The<br />Next Generation of Users</h1><p>2023&nbsp; · &nbsp;Mobile, Banking, Fintech</p></div><img src={heritageAssets.onboarding[1]} alt="Heritage Bank mobile app" /></section>
    <section className="heritageBrief"><aside><h3>Team</h3><p><b>2x</b> Product Designer<br /><b>1x</b> User Researcher<br /><b>1x</b> Product Manager<br /><b>2x</b> Mobile Developers<br /><b>2x</b> Backend Developers</p><h3>Timeline</h3><p>May ‘23 - Jan ‘24</p></aside><div><h2>A bit of context...</h2><p>Heritage Bank is one of Nigeria&apos;s commercial banks with over 2.3M depositors. Its mobile banking app had grown outdated, with clunky navigation, poor onboarding, inconsistent design, and no dark mode. These issues left users frustrated and stakeholders dissatisfied.</p><h2>My Role</h2><p>As lead product designer, I owned both UX and UI. I began with a UX audit and preliminary report, analyzing 200+ App Store reviews and benchmarking leading fintech apps. This revealed that onboarding and transfers were the biggest sources of frustration, while competitors set higher standards for navigation and clarity.</p><p>Guided by these insights, I redesigned onboarding flows to reduce early friction, introduced a token-based design system for scalability, and restructured navigation to bring core actions within one or two taps.</p><h2>Impact &amp; Results</h2><div className="heritageMetrics"><span><b>10k</b>Downloads in 1st month</span><span><b>97%</b>Unassisted onboarding</span><span><b>60%</b>Reduction in TTV</span></div></div></section>
    <section className="heritageFeature"><h2>Onboarding</h2><p>I redesigned the onboarding experience to distinguish between new users, returning customers, and Padie users. The new flow reduces friction and clarifies next steps with minimal cognitive load.</p><div className="heritageGrid three">{heritageAssets.onboarding.map((image, i) => <article key={image}><Visual src={image} alt="Onboarding screen" /><p>{["New users can setup a profile with an account number and OTP", "HB Padie users onboarded using their existing credentials, but will create a transaction PIN and set security questions.", "Returning users can login and jump right get back into it. Subsequent logins can be done with biometrics"][i]}</p></article>)}</div></section>
    <section className="heritageFeature"><h2>A New Home &amp; Navigation</h2><p>The Home screen was restructured to showcase relevant shortcuts like transfers, bills, and account history, making frequent actions more accessible.</p><div className="heritageGrid">{heritageAssets.home.map((image, i) => <article key={image}><Visual src={image} alt="Heritage Bank home screen" /><p>{i === 0 ? "I introduced a bottom navigation bar featuring the most-used sections; Home, Transactions, Self-Service, and Profile." : "Do More with Heritage Bank showcases relevant shortcuts like transfers, bills, and account history, making frequent actions more accessible."}</p></article>)}</div></section>
    <section className="heritageFeature"><h2>Transfers in Few Clicks</h2><p>I added intra-bank and interbank transfers as separate shortcuts on the home screen for easy access. Repeat transfers can be done with quick access to recent recipients.</p><div className="heritageGrid">{heritageAssets.transfers.map((image) => <article key={image}><Visual src={image} alt="Transfer flow" /><p>Intrabank Payments</p></article>)}</div></section>
    <section className="heritageFeature"><h2>Multi-Theme Compatibility</h2><p>I created a component-based system using tokens for colors, spacing, and typography, making it easy for engineers to switch themes or introduce new modules. The system is structured for easy maintenance and updates.</p><div className="heritageGrid"><Visual src={heritageAssets.system} alt="Heritage design system" /><Visual src={heritageAssets.system} alt="Heritage design system" /></div><div className="heritageSystem"><h2>Figma Variables, Tokens, &amp; Components</h2><p>I created a component-based system using tokens for colors, spacing, and typography, making it easy for engineers to switch themes or introduce new modules. The system is structured for easy maintenance and updates.</p></div></section>
    <div id="contact"><Contact /></div></main>;
}
export default async function CasePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const s = published.find((item) => item.slug === slug); if (!s) notFound();
  if (s.slug === "heritage-bank") return <HeritageCase />;
  const details = context[s.slug]; const nextStudies = details.next.map((next) => published.find((item) => item.slug === next)).filter(Boolean);
  return <main><SiteHeader /><article className="framerCase">
    <header className="framerCaseHero shell"><p className="caseEyebrow">{s.client}</p><h1>{s.title}</h1><p>{s.subtitle}</p></header>
    <div className="framerHeroImage shell"><img src={s.hero} alt={s.client + " project"} /></div>
    <section className="projectMeta shell"><div><span>Team</span><p>{details.team}</p></div><div><span>Timeline</span><p>{s.timeline}</p></div><div><span>Contributions</span><p>{details.contributions}</p></div></section>
    <section className="editorial shell"><h2>{details.opening}</h2><p>Our challenge was clear:</p><h1>{details.challenge}</h1></section>
    {details.shipped && <section className="showcase shell"><p>Shipped work</p><h1>Highlights of the revamp…</h1><img src={details.shipped} alt="Shipped product work" /></section>}
    {s.metrics && <section className="outcomes shell"><p>Results?</p><h1>We sure made an impact...</h1><p className="muted">{s.subtitle}</p><div>{s.metrics.map((m) => <article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div></section>}
    <section className="framerSections shell">{s.sections.map((section, index) => <section key={section.title}><p>{index === 0 ? "Background" : index === 1 ? "Getting the root..." : index === 2 ? "Our Solution" : "Reflections"}</p><h1>{section.title}</h1><h2>{section.body}</h2>{section.image && <div className="sectionVisual"><img src={section.image} alt={section.title} /></div>}</section>)}</section>
    <section className="nextCases shell"><p>Next?</p><h1>More Casestudies</h1><div>{nextStudies.map((item) => item && <a href={"/cases/" + item.slug} key={item.slug}><img src={item.hero} alt={item.client} /><span><small>{item.client}</small><small>{item.year}</small></span><h2>{item.title}</h2></a>)}</div></section>
  </article><Contact /></main>;
}
