import { notFound } from "next/navigation";
import { caseStudies } from "../../case-data";
import { Contact, SiteHeader } from "../../components";
const published = caseStudies.filter((s) => s.slug !== "conversational-ai");
const context: Record<string, { team: string; contributions: string; opening: string; challenge: string; shipped?: string; next: string[] }> = {
  "heritage-bank": { team: "2x Product Designer · 1x User Researcher · 1x Product Manager · 2x Mobile Developers · 2x Backend Developers", contributions: "UX Audit, Research, UX & UI Design", opening: "Heritage Bank is one of Nigeria’s commercial banks with over 2.3M depositors. Its mobile banking app had grown outdated, with clunky navigation, poor onboarding, inconsistent design, and no dark mode. These issues left users frustrated and stakeholders dissatisfied.", challenge: "How might we create a modern banking experience that makes onboarding, transfers and everyday actions clear, accessible and scalable?", next: ["mvno", "opscentral-case-study"] },
  mvno: { team: "2x Product Designer · 1x User Researcher · 1x Product Manager · 2x Mobile Developers · 2x Backend Developers", contributions: "Design, Strategy, Market Research & Usability Testing", opening: "Interswitch, the parent company of Verve with over 70M cardholders, wanted to build a direct-to-consumer channel beyond its traditional relationships through issuing banks and fintechs. Launching an MVNO under the Verve brand created an opportunity to deepen engagement with young people.", challenge: "How might we balance compliance, usability and adoption while helping young Nigerians stay connected, transact securely and be rewarded?", next: ["heritage-bank", "opscentral-case-study"] },
  "opscentral-case-study": { team: "Lead Product Designer @ Interswitch", contributions: "Design, Strategy, User Interviews", opening: "Interswitch processes over 1 billion transactions monthly across Africa. Partners often lacked a centralised way to track and manage transactions, forcing them to switch between back-office tools to investigate settlements, disputes and reports.", challenge: "How might we consolidate fragmented processes into a single, seamless experience that gives partners real-time transaction visibility?", next: ["heroshe-case-study", "heritage-bank"] },
  "heroshe-case-study": { team: "Full-time Designer at Heroshe", contributions: "Design, Strategy, User Interviews", opening: "Picture this: You find the perfect gadget on Amazon, but it can’t be delivered to your country. So you order and ship it to your freight-forwarder, and then… radio silence. The packages weren’t delayed or missing—but the updates were.", challenge: "How can we provide timely updates that keep users informed and confident about their shipments?", shipped: "https://framerusercontent.com/images/z3myjTjgaeus7bcMBDMbZhuks.png?scale-down-to=2048&width=2880&height=1616", next: ["opscentral-case-study", "heritage-bank"] },
};
export function generateStaticParams() { return published.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const s = published.find((item) => item.slug === slug); return { title: s ? s.title + " — Olusola Kalejaiye" : "Case Study" }; }
export default async function CasePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const s = published.find((item) => item.slug === slug); if (!s) notFound();
  const details = context[s.slug]; const nextStudies = details.next.map((next) => published.find((item) => item.slug === next)).filter(Boolean);
  return <main><SiteHeader /><article className="framerCase">
    <header className="framerCaseHero shell"><p className="caseEyebrow">{s.client}</p><h1>{s.title}</h1><p>{s.subtitle}</p></header>
    <div className="framerHeroImage shell"><img src={s.hero} alt={s.client + " project"} /></div>
    <section className="projectMeta shell"><div><span>Team</span><p>{details.team}</p></div><div><span>Timeline</span><p>{s.timeline}</p></div><div><span>Contributions</span><p>{details.contributions}</p></div></section>
    <section className="editorial shell"><h2>{details.opening}</h2><p>Our challenge was clear:</p><h1>{details.challenge}</h1></section>
    {details.shipped && <section className="showcase shell"><p>Shipped work</p><h1>Highlights of the revamp…</h1><img src={details.shipped} alt="Shipped product work" /></section>}
    {s.metrics && <section className="outcomes shell"><p>Results?</p><h1>We sure made an impact...</h1><p className="muted">{s.subtitle}</p><div>{s.metrics.map((m) => <article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div></section>}
    <section className="framerSections shell">{s.sections.map((section, index) => <section key={section.title}><p>{index === 0 ? "Background" : index === 1 ? "Getting the root..." : index === 2 ? "Our Solution" : "Reflections"}</p><h1>{section.title}</h1><h2>{section.body}</h2>{section.image && <div className="sectionVisual"><img src={section.image} alt={section.title} /></div>}</section>)}</section>
    <section className="nextCases shell"><p>Next?</p><h1>More Casestudies</h1><div>{nextStudies.map((item) => item && <a href={"/cases/" + item.slug} key={item.slug}><img src={item.hero} alt={item.client} /><span><small>{item.client}</small><small>{item.year}</small></span><h2>{item.title}</h2></a>)}</div></section>
  </article><Contact /></main>;
}
